### ISSUE TITLE
Problems on build Buendia-Server - Package does not exist

### ISSUE THREAD

**Issue by christianrafael** [projectbuendia/buendia#1]
Hi, i am following the documentation but on step of build ( mvn clean install ) i get the error below.

Any sugestions?

![buendia4](https://cloud.githubusercontent.com/assets/2487768/9796755/27eb9478-57ce-11e5-95ad-9a2f1ac4c02f.jpg)

**Comment by llvasconcellos** [comment]
Did you clone the buendia-libs repository? You need it to successfully build the server.

**Comment by christianrafael** [comment]
Yes

**Comment by christianrafael** [comment]
Problem solved.

https://github.com/projectbuendia/buendia/wiki/Development-Environment-On-Windows-With-Vagrant
