### ISSUE TITLE
UI: the plus for new patient and plus for icon are too similar.

### ISSUE THREAD

**Issue by Joronimo** [projectbuendia/buendia#110]
Ideally any button is easily identifiable as a button using the same graphic language for all buttons. 

Second, ideally no button is designed in a way that it could be confused for an icon. And same for icons being confused for buttons, though this one is usually harder to pull off because of the aesthetic nature of icons. 
![Screenshot_20190618-171204_Buendia](https://user-images.githubusercontent.com/24259037/59706103-4279ca80-91ef-11e9-91c1-60b805ba9f82.jpg)

**Comment by zestyping** [comment]
This has been fixed in the client.
