### ISSUE TITLE
UI: logout icon

### ISSUE THREAD

**Issue by Joronimo** [projectbuendia/buendia#111]
User logout is using an uncommonly known icon to layman users. Recommend: switching to text for logout or having text display under icon in small pt. for greater clarity.

Top right of image:
![Screenshot_20190618-173525_Buendia](https://user-images.githubusercontent.com/24259037/59706674-71dd0700-91f0-11e9-81b7-b9695e9a3db6.jpg)

**Comment by zestyping** [comment]
Login/logout UX is being reworked.
