### ISSUE TITLE
UX: edit patient birthdate 

### ISSUE THREAD

**Issue by Joronimo** [projectbuendia/buendia#112]
Currently the clinician is typing in the age of the patient in years and months separate. 

Would it be easier to have them type in the date of birth and have it automatically display age in years and months?
![Screenshot_20190618-174733_Buendia](https://user-images.githubusercontent.com/24259037/59707142-866dcf00-91f1-11e9-9324-e38c8b2782e1.jpg)

**Comment by zestyping** [comment]
The medics want to be able to enter years or months.
