### ISSUE TITLE
Yocto is not longer necessary

### ISSUE THREAD

**Issue by ivangayton** [projectbuendia/buendia#127]
Now that we no longer support the Intel Edison (and it is no longer manufactured, so don't talk to us about it anymore), we suspect that Moore's Law has ensured that we no longer need to use Yocto Linux, the ultralight distribution that ran on the Edison. On the Edison, in order to take advantage of Debian software repositories, we had an "inner" Debian installation in a chroot jail within the "outer" Yocto.

A small number of the tools in the Buendia setup still refer to the "outer" Yocto distribution (from within the debian chroot), and a few refer to stuff within the "inner" /debian directory from the Yocto. All this is, of course, no longer relevant. 

It probably affects our networking; most critically the DCHP and DNS stuff that the server is supposed to handle is set up using some of these scripts (notably .../buendia-networking/data/usr/share/buendia/config.d/networking)

# Files that contain any reference to Yocto

### ...buendia-networking/data/usr/share/buendia/config.d/networking
- /etc/network/interface configuration down and up involve buendia-enter-yocto
- DNS server up and down
- ap up and down
- Restart DHCP/DNS 

### /buendia-networking/control/prerm
Almost the whole thing is in an enter-yocto block

### /buendia-networking/control/postinst
Looks like very little of it will work. On the other hand, we don't know how much of it needs to exist or work!

### /utils/postinst
May not need to run if we aren't using Yocto (since we can just add things into systemd)
Buendia-divert aliases to get out of the chroot jail.
We can probably just settle for the stock Debian reboot 

### /devices/server/yocto/usr/local/bin/enter-debian
Probably irrelevant, since that location hasn't existed for some time!

### buendia/packages/buendia-networking/data/usr/bin/buendia-wifi-watchdog
Some of it refers to enter-yocto (may be related to logging wifi uptime)

### buendia/tools/make_release_package
Not sure what this does. Is it an outdated utility? 

# Files that refer to /debian (the chroot jail from the old Yocto setup)
### buendia-utils
This is related to the reboot aliasing (that goes into a 5-second loop)

**Comment by schuyler** [comment]
This issue was closed by #136
