### ISSUE TITLE
buendia-pkgserver leaves empty temp directories

### ISSUE THREAD

**Issue by schuyler** [projectbuendia/buendia#145]
Specifically, some process is creating `/mnt/buendia-pkgserver-import.nnnn` and `/usr/share/buendia/packages.import.nnnn` directories whenever a USB stick is inserted, but then not cleaning them up.

**Comment by schuyler** [comment]
This issue definitely doesn't happen all the time, and may be related to #149?

**Comment by zestyping** [comment]
These directories are created by `buendia-pkgserver-import`:

```
love[10026] tools/package_grep 'mnt.*$$'
buendia-pkgserver/data/usr/bin/buendia-pkgserver-import:    mntdir=/mnt/$name.$$
love[10027] tools/package_grep 'import.*$$'
buendia-pkgserver/data/usr/bin/buendia-pkgserver-import:pkgdir=${package_repo}.import.$$
```

Also a much lower priority than backup and restore right now.  We can easily do software updates by hand.  We cannot do backup and restore by hand.
