### ISSUE TITLE
Port 9000 is blocked by the MSF office firewall

### ISSUE THREAD

**Issue by zestyping** [projectbuendia/buendia#224]
Unfortunately, the Internet access setup at the MSF offices in Goma and Bunia blocks access to some websites and ports.  Among them is port 9000, which means no access to OpenMRS via the office Wi-Fi, which among other things impedes training and self-education.

**Comment by schuyler** [comment]
@zestyping Do we want a site configuration option to allow putting OpenMRS on a different port?

**Comment by zestyping** [comment]
I don't think we need to make this configurable.  If we expose everything at port 80, that makes a lot of things easier—no more telling people to type ":9000", and hyperlinks work (hooray).  This is the approach I'm taking in the `ping/dashboard-redesign` branch.
