### ISSUE TITLE
Update script not updating everything

### ISSUE THREAD

**Issue by dancunningham** [projectbuendia/buendia#36]
There's still something wrong with our buendia-update script.

The apt-get command is not necessarily updating all the packages to the latest version.

For example at the moment after it has updated dev to build 566, this is the result:

```
jenkins@openmrs-2:~$ buendia-status 
 12:54:29 up 22 days, 10:25,  1 user,  load average: 0.55, 0.71, 0.38
ii  buendia-db           0.0.566         0.0.566-compatible Buendia database st
ii  buendia-db-init      0.0.499         Initial data for the Buendia database 
ii  buendia-db-migrate   0.0.470         Migrates a Buendia database from versi
ii  buendia-monitoring   0.0.467         Monitoring and log rotation for Buendi
ii  buendia-mysql        0.0.498         MySQL server configured for Buendia   
ii  buendia-openmrs      0.0.499         OpenMRS configured for Buendia        
ii  buendia-pkgserver    0.0.467         Serves up Buendia .deb and .apk files 
ii  buendia-server       0.0.566         Buendia API server (an OpenMRS module)
un  buendia-site                                                               
ii  buendia-site-dev     0.0.467         Site config: Cloud - Development      
ii  buendia-sshd         0.0.467         sshd configured for Buendia           
ii  buendia-tomcat7      0.0.467         Tomcat 7 configured for Buendia       
ii  buendia-update       0.0.467         Keeps Buendia packages installed and u
ii  buendia-utils        0.0.467         Utility scripts for Buendia           
UPDATE_AUTOUPDATE is currently disabled.
Keeping updated: buendia-backup buendia-dashboard buendia-db-migrate
    buendia-monitoring buendia-pkgserver buendia-pushclock buendia-server
    buendia-site-dev buendia-sshd buendia-update buendia-utils
```

Lots of the packages are still at build 467, which was 27 July 2015.

For most of them, that's fine, they haven't been changed since April.

But, two of them have:

buendia-site-dev was updated in September by commit 77ffcfc.
buendia-utils was updated in August 2015 by commit e5d4857.

Can/should we force it to update all buendia packages to the latest build?

**Comment by capnfabs** [comment]
FYI - I found out when I was digging yesterday that the script intentionally only updates buendia-server, which has a dependency on buendia-db. That's why only those two packages keep getting updated.

**Comment by schuyler** [comment]
@zestyping should `buendia-update` update everything? or just `buendia-server`?

**Comment by schuyler** [comment]
Closing this issue as it is somewhat out of date, and we have more recent (and more specific) issues related to buendia-update

**Comment by zestyping** [comment]
@schuyler It updates the packages in `packages.list.d`.  That's what `packages.list.d` is for.
